# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  NewCops: enable
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Max: 45
Metrics/BlockLength:
  Max: 40
Metrics/MethodLength:
  Max: 40
Metrics/ClassLength:
  Max: 180
Metrics/ParameterLists:
  Max: 7
Layout/ParameterAlignment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
