AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/AbcSize:
  Max: 45
Metrics/BlockLength:
  Max: 30
Metrics/MethodLength:
  Max: 40
Metrics/ClassLength:
  Max: 180
Metrics/ParameterLists:
  Max: 7
Layout/AlignParameters:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20
