language: ruby
rvm:
  - 2.6.0
cache: bundler
branches:
  only:
    - master
install:
  - travis_retry bundle update
  - gem install pdd
script:
  - pdd -f /dev/null
  - export RUBYOPT="-W0"
  - rake --quiet
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
